In [1]:
import numpy as np

In [23]:
# Q1- construct 1d numpy array, 2d numpy array,3d numpy array.
oned_array = np.array([1,2,3])
print('1D Array : \n', oned_array)

twod_array = np.array([[1,2,3], [4,5,6], [7,8,9]])
print('2D Array : \n', twod_array)

threed_array = np.array([[[1,2,3], [4,5,6], [7,8,9]],
                         [[11,21,31], [41,51,61], [7,18,9]],
                         [[1,2,23], [4,5,63], [7,8,94]]])
print('3D Array : \n', threed_array)

1D Array : 
 [1 2 3]
2D Array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
3D Array : 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 21 31]
  [41 51 61]
  [ 7 18  9]]

 [[ 1  2 23]
  [ 4  5 63]
  [ 7  8 94]]]


In [32]:
# Q2- Write a NumPy program to test whether any of the elements of a given
# array is non-zero. Hint use any()
print(oned_array.any())

True


In [37]:
# Q3- Write a NumPy program to create an array of 10 zeros, 10 ones, 10 fives
array1 = []
for i in [0, 1, 5]:
    array1.append(i * np.ones([10]))
array1 = np.array(array1)
print(array1)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]


In [42]:
# Q4- Write a NumPy program to create an array of 10 zeros 3d
zeros = np.zeros([3,10,10])
print(zeros)

[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0

In [67]:
# Q5- Write a NumPy program to create an array of the integers from 30 to 70.
array2 = np.arange(30,70)
print(array2)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [50]:
# Q6- Write a NumPy program to create a 3x3 identity matrix.
ones_3d = np.ones([3,3])
print(ones_3d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [66]:
# Q7- Write a NumPy program to generate a random number between 0 and 1.
rand_num = np.random.rand()
print(rand_num)

0.1459678633355056


In [68]:
# Q8- Write a NumPy program to create a 3X4 array using and iterate over it.
a = np.arange(10,22).reshape((3, 4))
print("Original array:")
print(a)
print("Each element of the array is:")
for x in np.nditer(a):
  print(x,end=" ")

Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 

In [79]:
# Q9- Write a NumPy program to create a 10x10 matrix, in which the elements on
# the borders will be equal to 1, and inside 0.
mat = np.ones([10,10])
mat[1:-1, 1:-1] = 0
print(mat)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
